kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod_admin
  namespace: prod
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: prod_admin
  namespace: prod
subjects:
- kind: User
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io