kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment_view
  namespace: default
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: deploy_view
  namespace: default
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment_view
  apiGroup: rbac.authorization.k8s.io